---
name: Homebrew Stable

on:
  push:
    branches:
      - master
    paths:
      - HomebrewFormula/**
      - .github/workflows/homebrew-stable.yml

jobs:
  install:
    runs-on: [macOS-latest]
    steps:
      - name: Set up
        run: |
          brew update-reset
          brew --env
          brew config
          export HOMEBREW_NO_AUTO_UPDATE=1
          git config --global credential.helper ""
          git config --global --add credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" >> ~/.git-credentials
          git config --global url."https://github.com/".insteadof git@github.com:

      - name: Brew tap
        run: |
          brew tap koordinates/sno git@github.com:koordinates/sno.git

      - name: Brew install
        run: |
          brew install --display-times sno

      - name: Brew tests
        run: |
          brew install --only-dependencies --include-test sno
          brew test sno
