---
name: Homebrew Dev

on: [push]

jobs:
  build:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Set up Homebrew
        run: |
          brew update-reset
          brew --env
          brew config
          export HOMEBREW_NO_AUTO_UPDATE=1

      - name: Brew audit
        run: brew audit --strict --except=specs HomebrewFormula/sno.rb

      - name: Brew install --head [master]
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global credential.helper ""
          git config --global --add credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" >> ~/.git-credentials
          git config --global url."https://github.com/".insteadof git@github.com:

          mkdir "$(brew --repo)/Library/Taps/koordinates"
          ln -s "$(pwd)" "$(brew --repo)/Library/Taps/koordinates/homebrew-sno"
          brew tap --repair

          brew install --HEAD --only-dependencies --include-test koordinates/sno/sno
          brew install -v --HEAD --display-times koordinates/sno/sno

      - name: Brew install --devel [non-master]
        if: github.ref != 'refs/heads/master'
        run: |
          brew install --devel --only-dependencies --include-test HomebrewFormula/sno.rb
          brew install -v --devel --display-times HomebrewFormula/sno.rb
        env:
          # Hacky workaround for Homebrew env var filtering
          HOMEBREW_GITHUB_REF: ${{ github.ref }}

      - name: Brew test [master]
        if: github.ref == 'refs/heads/master'
        run: brew test -v --HEAD koordinates/sno/sno

      - name: Brew test [non-master]
        if: github.ref != 'refs/heads/master'
        run: brew test -v sno
