---
name: Homebrew Stable

on:
  push:
    branches:
      - master
    paths:
      - HomebrewFormula/**
      - .github/workflows/homebrew-stable.yml

jobs:
  install:
    runs-on: [macOS-latest]
    steps:
      - name: Set up
        run: |
          brew update-reset
          brew --env
          brew config
          export HOMEBREW_NO_AUTO_UPDATE=1
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:@github.com/".insteadOf git@github.com:

      - name: Brew tap
        run: |
          env
          git config --list | grep instead
          brew tap -d koordinates/sno git@github.com:koordinates/sno.git

      - name: Brew install
        run: |
          brew install -v --display-times sno

      - name: Brew tests
        run: |
          brew install --only-dependencies --include-test sno
          brew test -v sno
